export interface Trip {
  id: string;
  title: string;
  subtitle: string;
  region: string;
  description: string;
  duration: string;
  durationDays: number;
  price: string;
  priceValue: number;
  image: string;
  heroImage: string;
  highlights: string[];
  tags: string[];
}

export const trips: Trip[] = [
  // ==================== SUDAMÉRICA ====================
  {
    id: 'bariloche',
    title: 'Bariloche',
    subtitle: 'Patagonia Argentina',
    region: 'sudamerica',
    description: 'Descubrí la magia de la Patagonia argentina en San Carlos de Bariloche. Lagos cristalinos, montañas nevadas, bosques milenarios y la mejor gastronomía regional te esperan.',
    duration: '7 días',
    durationDays: 7,
    price: 'Desde USD $1.200',
    priceValue: 1200,
    image: '/bariloche-patagonia-argentina-mountains-lake-sceni.jpg',
    heroImage: '/bariloche-patagonia-argentina-panoramic-view-mount.jpg',
    highlights: ['Circuito Chico', 'Cerro Catedral', 'Isla Victoria', 'Chocolaterías artesanales'],
    tags: ['montaña', 'naturaleza', 'gastronomía', 'lagos'],
  },
  {
    id: 'cataratas',
    title: 'Cataratas del Iguazú',
    subtitle: 'Misiones, Argentina',
    region: 'sudamerica',
    description: 'Una de las siete maravillas naturales del mundo te espera. Viví la experiencia de las Cataratas del Iguazú con paseos en lancha, caminatas por la selva y vistas impresionantes.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $950',
    priceValue: 950,
    image: '/iguazu-falls-waterfall-argentina-brazil-majestic.jpg',
    heroImage: '/iguazu-falls-panoramic-rainbow-mist-waterfall.jpg',
    highlights: ['Garganta del Diablo', 'Paseo en lancha', 'Selva Misionera', 'Minas de Wanda'],
    tags: ['naturaleza', 'aventura', 'cataratas', 'selva'],
  },
  {
    id: 'mendoza',
    title: 'Mendoza',
    subtitle: 'Región de Cuyo, Argentina',
    region: 'sudamerica',
    description: 'La tierra del sol y del buen vino. Recorré las bodegas más prestigiosas, disfrutá de paisajes andinos únicos y descubrí la calidez de la cultura mendocina.',
    duration: '4 días',
    durationDays: 4,
    price: 'Desde USD $850',
    priceValue: 850,
    image: '/mendoza-argentina-vineyards-andes-mountains-wine-c.jpg',
    heroImage: '/mendoza-vineyards-sunset-andes-mountains-panoramic.jpg',
    highlights: ['Ruta del Vino', 'Alta Montaña', 'Puente del Inca', 'Parque San Martín'],
    tags: ['vino', 'montaña', 'gastronomía', 'cultura'],
  },
  {
    id: 'salta',
    title: 'Salta y Jujuy',
    subtitle: 'Norte Argentino',
    region: 'sudamerica',
    description: 'Colores, historia y tradiciones en el norte argentino. Desde la Quebrada de Humahuaca hasta los Valles Calchaquíes, cada rincón es una postal inolvidable.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $1.100',
    priceValue: 1100,
    image: '/salta-jujuy-argentina-colorful-mountains-cerro-sie.jpg',
    heroImage: '/quebrada-humahuaca-colorful-mountains-panoramic-ar.jpg',
    highlights: ['Cerro de los 7 Colores', 'Salinas Grandes', 'Cafayate', 'Tren a las Nubes'],
    tags: ['cultura', 'historia', 'paisajes', 'tradiciones'],
  },
  {
    id: 'ushuaia',
    title: 'Ushuaia',
    subtitle: 'Fin del Mundo, Argentina',
    region: 'sudamerica',
    description: 'Llegá al fin del mundo y descubrí paisajes únicos. Glaciares, montañas, lagos y el Canal Beagle te esperan en la ciudad más austral del planeta.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.400',
    priceValue: 1400,
    image: '/ushuaia-tierra-del-fuego-end-of-world-argentina.jpg',
    heroImage: '/ushuaia-beagle-channel-panoramic-mountains-snow.jpg',
    highlights: ['Parque Nacional', 'Canal Beagle', 'Tren del Fin del Mundo', 'Pingüinera'],
    tags: ['aventura', 'naturaleza', 'fauna', 'glaciares'],
  },
  {
    id: 'calafate',
    title: 'El Calafate',
    subtitle: 'Glaciar Perito Moreno, Argentina',
    region: 'sudamerica',
    description: 'El glaciar más famoso del mundo te espera. Caminá sobre el hielo, navegá entre icebergs y viví una experiencia única en la Patagonia austral.',
    duration: '4 días',
    durationDays: 4,
    price: 'Desde USD $1.300',
    priceValue: 1300,
    image: '/el-calafate-perito-moreno-glacier-argentina-blue-i.jpg',
    heroImage: '/placeholder.svg?height=800&width=1600',
    highlights: ['Glaciar Perito Moreno', 'Minitrekking', 'Glaciar Upsala', 'Estancias patagónicas'],
    tags: ['glaciares', 'aventura', 'naturaleza', 'trekking'],
  },
  {
    id: 'rio-de-janeiro',
    title: 'Río de Janeiro',
    subtitle: 'Brasil',
    region: 'sudamerica',
    description: 'La ciudad maravillosa te espera con sus playas icónicas, el Cristo Redentor y una vibrante cultura. Copacabana, Ipanema y el Pan de Azúcar son solo el comienzo de esta aventura tropical.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $1.100',
    priceValue: 1100,
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1600&h=800&fit=crop',
    highlights: ['Cristo Redentor', 'Pan de Azúcar', 'Copacabana', 'Sambódromo'],
    tags: ['playa', 'cultura', 'naturaleza', 'fiesta'],
  },
  {
    id: 'galapagos',
    title: 'Islas Galápagos',
    subtitle: 'Ecuador',
    region: 'sudamerica',
    description: 'Un paraíso de biodiversidad único en el planeta. Descubrí tortugas gigantes, iguanas marinas, leones marinos y aves exóticas en el archipiélago que inspiró a Darwin.',
    duration: '8 días',
    durationDays: 8,
    price: 'Desde USD $3.200',
    priceValue: 3200,
    image: '/galapagos_leon_dormido.jpeg',
    heroImage: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1600&h=800&fit=crop',
    highlights: ['Tortugas Gigantes', 'Snorkel con tiburones', 'Isla Isabela', 'Estación Charles Darwin'],
    tags: ['naturaleza', 'fauna', 'aventura', 'buceo'],
  },

  // ==================== NORTEAMÉRICA Y CARIBE ====================
  {
    id: 'nueva-york',
    title: 'Nueva York',
    subtitle: 'Estados Unidos',
    region: 'norteamerica',
    description: 'La ciudad que nunca duerme te espera con sus rascacielos icónicos, Broadway, Central Park y una infinita oferta cultural y gastronómica. Viví el sueño americano en la Gran Manzana.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $2.100',
    priceValue: 2100,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1600&h=800&fit=crop',
    highlights: ['Times Square', 'Estatua de la Libertad', 'Central Park', 'Empire State'],
    tags: ['ciudad', 'cultura', 'compras', 'gastronomía'],
  },
  {
    id: 'cancun',
    title: 'Cancún y Riviera Maya',
    subtitle: 'México',
    region: 'norteamerica',
    description: 'Playas de arena blanca, aguas turquesas y la magia de la cultura maya. Desde las ruinas de Tulum hasta los cenotes sagrados, descubrí el paraíso caribeño mexicano.',
    duration: '7 días',
    durationDays: 7,
    price: 'Desde USD $1.500',
    priceValue: 1500,
    image: 'https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=1600&h=800&fit=crop',
    highlights: ['Ruinas de Tulum', 'Cenotes', 'Chichén Itzá', 'Isla Mujeres'],
    tags: ['playa', 'cultura', 'arqueología', 'relax'],
  },
  {
    id: 'puerto-rico',
    title: 'San Juan',
    subtitle: 'Puerto Rico',
    region: 'caribe',
    description: 'Historia colonial española, playas paradisíacas y la mejor salsa del Caribe. Explorá el Viejo San Juan, El Morro y la bioluminiscente Bahía Mosquito en esta isla encantadora.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.400',
    priceValue: 1400,
    image: 'https://images.unsplash.com/photo-1579687196544-08ae57ab5966?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=1600&h=800&fit=crop',
    highlights: ['Viejo San Juan', 'El Morro', 'Bahía Bioluminiscente', 'El Yunque'],
    tags: ['playa', 'historia', 'cultura', 'naturaleza'],
  },
  {
    id: 'cuba',
    title: 'La Habana',
    subtitle: 'Cuba',
    region: 'caribe',
    description: 'Un viaje en el tiempo a la Cuba auténtica. Autos clásicos, música en vivo, el Malecón y una cultura vibrante te esperan en esta isla caribeña llena de historia y encanto.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $1.300',
    priceValue: 1300,
    image: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1570299437522-462d73b3ed03?w=1600&h=800&fit=crop',
    highlights: ['Habana Vieja', 'El Malecón', 'Varadero', 'Trinidad'],
    tags: ['historia', 'cultura', 'playa', 'música'],
  },

  // ==================== EUROPA ====================
  {
    id: 'paris',
    title: 'París',
    subtitle: 'Francia',
    region: 'europa',
    description: 'La ciudad del amor te espera con la Torre Eiffel, el Louvre, los Campos Elíseos y una gastronomía inigualable. Perdete en sus cafés, museos y encantadores barrios parisinos.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $2.200',
    priceValue: 2200,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1600&h=800&fit=crop',
    highlights: ['Torre Eiffel', 'Museo del Louvre', 'Montmartre', 'Versalles'],
    tags: ['cultura', 'gastronomía', 'arte', 'romántico'],
  },
  {
    id: 'barcelona',
    title: 'Barcelona',
    subtitle: 'España',
    region: 'europa',
    description: 'Arte, arquitectura modernista y playas mediterráneas. Descubrí las obras de Gaudí, el Barrio Gótico, Las Ramblas y la vibrante vida nocturna de la capital catalana.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.800',
    priceValue: 1800,
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1600&h=800&fit=crop',
    highlights: ['Sagrada Familia', 'Park Güell', 'Las Ramblas', 'Barrio Gótico'],
    tags: ['cultura', 'arte', 'playa', 'gastronomía'],
  },
  {
    id: 'roma',
    title: 'Roma',
    subtitle: 'Italia',
    region: 'europa',
    description: 'La Ciudad Eterna te transporta a través de milenios de historia. El Coliseo, el Vaticano, la Fontana di Trevi y una gastronomía sublime te esperan en la cuna del Imperio Romano.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $2.000',
    priceValue: 2000,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=1600&h=800&fit=crop',
    highlights: ['Coliseo', 'Vaticano', 'Fontana di Trevi', 'Foro Romano'],
    tags: ['historia', 'cultura', 'arte', 'gastronomía'],
  },
  {
    id: 'londres',
    title: 'Londres',
    subtitle: 'Reino Unido',
    region: 'europa',
    description: 'Tradición y modernidad se fusionan en la capital británica. El Big Ben, el Palacio de Buckingham, los museos de clase mundial y la diversa escena cultural te esperan.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $2.300',
    priceValue: 2300,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=1600&h=800&fit=crop',
    highlights: ['Big Ben', 'Tower of London', 'British Museum', 'Camden Town'],
    tags: ['cultura', 'historia', 'compras', 'museos'],
  },
  {
    id: 'berlin',
    title: 'Berlín',
    subtitle: 'Alemania',
    region: 'europa',
    description: 'Una ciudad que renació de la historia. Desde los restos del Muro hasta la vibrante escena artística y nocturna, Berlín es un destino que combina historia, cultura y vanguardia.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.700',
    priceValue: 1700,
    image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1587330979470-3595ac045ab0?w=1600&h=800&fit=crop',
    highlights: ['Puerta de Brandeburgo', 'Muro de Berlín', 'Isla de los Museos', 'Reichstag'],
    tags: ['historia', 'cultura', 'arte', 'vida nocturna'],
  },
  {
    id: 'cracovia',
    title: 'Cracovia',
    subtitle: 'Polonia',
    region: 'europa',
    description: 'La joya medieval de Europa del Este. Un centro histórico Patrimonio de la Humanidad, las minas de sal de Wieliczka y la conmovedora historia de Auschwitz te esperan.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.200',
    priceValue: 1200,
    image: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1574077579843-91b1997a959f?w=1600&h=800&fit=crop',
    highlights: ['Plaza del Mercado', 'Castillo de Wawel', 'Minas de Sal', 'Barrio Judío'],
    tags: ['historia', 'cultura', 'arquitectura', 'gastronomía'],
  },
  {
    id: 'malta',
    title: 'Malta',
    subtitle: 'República de Malta',
    region: 'europa',
    description: 'Una isla mediterránea con 7.000 años de historia. Templos megalíticos, ciudades fortificadas, aguas cristalinas y la famosa Gruta Azul te esperan en este pequeño paraíso.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $1.400',
    priceValue: 1400,
    image: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1568702846914-96b305d2uj8a?w=1600&h=800&fit=crop',
    highlights: ['La Valeta', 'Mdina', 'Gruta Azul', 'Templos de Ħaġar Qim'],
    tags: ['historia', 'playa', 'cultura', 'arquitectura'],
  },
  {
    id: 'santorini',
    title: 'Santorini',
    subtitle: 'Grecia',
    region: 'europa',
    description: 'Las icónicas casas blancas con cúpulas azules sobre acantilados volcánicos. Puestas de sol legendarias, playas de arena negra y la mejor gastronomía griega en este paraíso del Egeo.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $2.100',
    priceValue: 2100,
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1600&h=800&fit=crop',
    highlights: ['Oia', 'Fira', 'Playa Roja', 'Caldera Volcánica'],
    tags: ['romántico', 'playa', 'gastronomía', 'paisajes'],
  },

  // ==================== ESCANDINAVIA ====================
  {
    id: 'laponia',
    title: 'Laponia',
    subtitle: 'Finlandia',
    region: 'escandinavia',
    description: 'El hogar de Papá Noel y las auroras boreales. Trineos de huskies, saunas finlandesas, iglús de cristal y la magia del Ártico te esperan en este destino de ensueño invernal.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $3.500',
    priceValue: 3500,
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?w=1600&h=800&fit=crop',
    highlights: ['Auroras Boreales', 'Pueblo de Santa Claus', 'Safari de Huskies', 'Iglús de cristal'],
    tags: ['aventura', 'naturaleza', 'invierno', 'auroras'],
  },
  {
    id: 'fiordos-noruega',
    title: 'Fiordos Noruegos',
    subtitle: 'Noruega',
    region: 'escandinavia',
    description: 'Paisajes de ensueño entre montañas y mar. Navegá por los majestuosos fiordos, descubrí pueblos vikingos y maravillate con cascadas, glaciares y la naturaleza más espectacular de Europa.',
    duration: '8 días',
    durationDays: 8,
    price: 'Desde USD $3.800',
    priceValue: 3800,
    image: 'https://images.unsplash.com/photo-1520769945061-0a448c463865?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&h=800&fit=crop',
    highlights: ['Fiordo de Geiranger', 'Bergen', 'Tren de Flåm', 'Preikestolen'],
    tags: ['naturaleza', 'aventura', 'paisajes', 'crucero'],
  },
  {
    id: 'estocolmo',
    title: 'Estocolmo',
    subtitle: 'Suecia',
    region: 'escandinavia',
    description: 'La Venecia del Norte construida sobre 14 islas. Museos de clase mundial, el casco antiguo de Gamla Stan, diseño escandinavo y una escena gastronómica innovadora te esperan.',
    duration: '5 días',
    durationDays: 5,
    price: 'Desde USD $2.400',
    priceValue: 2400,
    image: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1572969057163-c56aa453cdbe?w=1600&h=800&fit=crop',
    highlights: ['Gamla Stan', 'Museo Vasa', 'Palacio Real', 'Archipiélago'],
    tags: ['cultura', 'diseño', 'historia', 'naturaleza'],
  },
  {
    id: 'copenhague',
    title: 'Copenhague',
    subtitle: 'Dinamarca',
    region: 'escandinavia',
    description: 'La capital del hygge y el diseño nórdico. Jardines de Tivoli, la Sirenita, coloridos edificios en Nyhavn y la mejor gastronomía nueva nórdica en la ciudad más feliz del mundo.',
    duration: '4 días',
    durationDays: 4,
    price: 'Desde USD $2.200',
    priceValue: 2200,
    image: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1552560880-2482cef14240?w=1600&h=800&fit=crop',
    highlights: ['Nyhavn', 'Jardines de Tivoli', 'La Sirenita', 'Christiania'],
    tags: ['cultura', 'diseño', 'gastronomía', 'bicicletas'],
  },

  // ==================== MEDIO ORIENTE ====================
  {
    id: 'dubai',
    title: 'Dubái',
    subtitle: 'Emiratos Árabes Unidos',
    region: 'medio-oriente',
    description: 'La ciudad del futuro en el desierto. El Burj Khalifa, islas artificiales, souks tradicionales y experiencias de lujo incomparables. Donde la tradición árabe se encuentra con la modernidad extrema.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $2.800',
    priceValue: 2800,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1600&h=800&fit=crop',
    highlights: ['Burj Khalifa', 'Palm Jumeirah', 'Safari en el desierto', 'Dubai Mall'],
    tags: ['lujo', 'arquitectura', 'compras', 'desierto'],
  },

  // ==================== ASIA ====================
  {
    id: 'tokio',
    title: 'Tokio',
    subtitle: 'Japón',
    region: 'asia',
    description: 'Tradición milenaria y tecnología de vanguardia. Templos antiguos, barrios futuristas como Shibuya, la mejor gastronomía del mundo y la cultura más fascinante de Asia te esperan.',
    duration: '10 días',
    durationDays: 10,
    price: 'Desde USD $4.200',
    priceValue: 4200,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1600&h=800&fit=crop',
    highlights: ['Templo Senso-ji', 'Shibuya Crossing', 'Monte Fuji', 'Kioto'],
    tags: ['cultura', 'gastronomía', 'tecnología', 'tradición'],
  },
  {
    id: 'kuala-lumpur',
    title: 'Kuala Lumpur',
    subtitle: 'Malasia',
    region: 'asia',
    description: 'Una metrópolis multicultural donde conviven mezquitas, templos hindúes y rascacielos modernos. Las Torres Petronas, cuevas Batu y una gastronomía de fusión única te esperan.',
    duration: '6 días',
    durationDays: 6,
    price: 'Desde USD $1.800',
    priceValue: 1800,
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1508062878650-88b52897f298?w=1600&h=800&fit=crop',
    highlights: ['Torres Petronas', 'Cuevas Batu', 'Chinatown', 'Selva de Taman Negara'],
    tags: ['cultura', 'naturaleza', 'gastronomía', 'arquitectura'],
  },

  // ==================== OCEANÍA ====================
  {
    id: 'sydney',
    title: 'Sídney',
    subtitle: 'Australia',
    region: 'oceania',
    description: 'La ciudad más icónica de Oceanía. La Ópera de Sídney, el Harbour Bridge, playas doradas como Bondi y la Gran Barrera de Coral a tu alcance en este destino imperdible.',
    duration: '10 días',
    durationDays: 10,
    price: 'Desde USD $4.500',
    priceValue: 4500,
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1600&h=800&fit=crop',
    highlights: ['Ópera de Sídney', 'Harbour Bridge', 'Bondi Beach', 'Blue Mountains'],
    tags: ['playa', 'naturaleza', 'cultura', 'aventura'],
  },
];

export function getTripById(id: string): Trip | undefined {
  return trips.find((trip) => trip.id === id);
}

export function getRegions(): string[] {
  return [...new Set(trips.map((trip) => trip.region))];
}

export function getAllTags(): string[] {
  const allTags = trips.flatMap((trip) => trip.tags);
  return [...new Set(allTags)];
}
